easy_admin:
    entities:
        # List the entity class name you want to manage
        Conference: 
            class: App\Entity\Conference
        Comment: 
            class: App\Entity\Comment
            form:
              fields:
                - {property: 'photoFile', type: 'VichImageType'}
        User: 
            class: App\Entity\User
